<?php /* @var $this Slim\Views\PhpRenderer */ ?>
<div class="joinus">
  <h1 class="title"><?php // echo $data['header'];  ?></h1>
  <h4 class="sub-title"><?php // echo $data['subheader'];  ?></h4>
  <form method="post" action="">
    <div class="form-content">
      <div class="form-col">
        <input type="text" name="email" class="form-input" placeholder="E-Mail" required>
      </div>

      <div class="form-col">
        <button type="submit" class="form-btn">Submit</button>
      </div>

      <div class="form-col">
        Already have an account?
        Click <a href="https://<?php echo $team_name; ?>.slack.com/">here</a> to login.
      </div>
    </div>
  </form>
</div>
